# Generated by Django 3.0.5 on 2020-04-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0002_auto_20200418_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguesa',
            name='ingredients',
            field=models.ManyToManyField(to='consumo.Ingredientes'),
        ),
    ]
