# Generated by Django 3.0.5 on 2020-04-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0003_hamburguesa_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientes',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
