# Generated by Django 3.0.5 on 2020-04-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
